import bcrypt from 'bcryptjs';

const now = Date.now();
const day = 24 * 60 * 60 * 1000;
const hash = (pw) => bcrypt.hashSync(pw, 8);

function tx(symbol, side, quantity, price, daysAgo) {
  return {
    id: `${symbol}-${side}-${daysAgo}-${Math.round(price)}`,
    symbol,
    side,
    quantity,
    price,
    timestamp: now - daysAgo * day,
  };
}

export function seedData() {
  return {
    users: [
      {
        id: 'admin-1',
        name: 'Administrador',
        email: 'admin@simtrade.com',
        passwordHash: hash('admin123'),
        role: 'admin',
        status: 'active',
        kycStatus: 'verified',
        createdAt: now - 120 * day,
        lastActiveAt: now - 1 * 60 * 1000,
        virtualBalance: 10000,
        holdings: [],
        transactions: [],
        tags: [],
        notes: [],
      },
      {
        id: 'user-1',
        name: 'María Rodríguez',
        email: 'maria@example.com',
        passwordHash: hash('demo1234'),
        role: 'user',
        status: 'active',
        kycStatus: 'verified',
        createdAt: now - 45 * day,
        lastActiveAt: now - 2 * 60 * 60 * 1000,
        virtualBalance: 7420.5,
        holdings: [
          { symbol: 'BTCUSD', quantity: 0.02, avgPrice: 61000 },
          { symbol: 'AAPL', quantity: 5, avgPrice: 192.3 },
        ],
        transactions: [
          tx('BTCUSD', 'buy', 0.02, 61000, 12),
          tx('AAPL', 'buy', 5, 192.3, 8),
          tx('ETHUSD', 'buy', 0.5, 1580, 5),
          tx('ETHUSD', 'sell', 0.5, 1620, 2),
        ],
        tags: ['vip', 'activo'],
        notes: [
          { id: 'n1', text: 'Cliente muy activo, opera cripto a diario.', at: now - 3 * day, by: 'Administrador' },
        ],
      },
      {
        id: 'user-2',
        name: 'Carlos Méndez',
        email: 'carlos@example.com',
        passwordHash: hash('demo1234'),
        role: 'user',
        status: 'active',
        kycStatus: 'pending',
        createdAt: now - 10 * day,
        lastActiveAt: now - 1 * day,
        virtualBalance: 9800,
        holdings: [{ symbol: 'TSLA', quantity: 2, avgPrice: 245 }],
        transactions: [tx('TSLA', 'buy', 2, 245, 3)],
        tags: ['nuevo'],
        notes: [],
      },
      {
        id: 'user-3',
        name: 'Lucía Fernández',
        email: 'lucia@example.com',
        passwordHash: hash('demo1234'),
        role: 'user',
        status: 'active',
        kycStatus: 'verified',
        createdAt: now - 30 * day,
        lastActiveAt: now - 5 * day,
        virtualBalance: 12500,
        holdings: [{ symbol: 'ETHUSD', quantity: 1.5, avgPrice: 1600 }],
        transactions: [tx('ETHUSD', 'buy', 1.5, 1600, 6), tx('NVDA', 'buy', 3, 130, 20), tx('NVDA', 'sell', 3, 138, 14)],
        tags: ['vip'],
        notes: [{ id: 'n2', text: 'Solicitó información sobre límites de retiro (demo).', at: now - 7 * day, by: 'Administrador' }],
      },
      {
        id: 'user-4',
        name: 'Diego Torres',
        email: 'diego@example.com',
        passwordHash: hash('demo1234'),
        role: 'user',
        status: 'suspended',
        kycStatus: 'none',
        createdAt: now - 60 * day,
        lastActiveAt: now - 40 * day,
        virtualBalance: 3200,
        holdings: [],
        transactions: [tx('SOLUSD', 'buy', 10, 70, 42), tx('SOLUSD', 'sell', 10, 68, 41)],
        tags: ['riesgo'],
        notes: [{ id: 'n3', text: 'Cuenta suspendida por actividad inusual (simulado).', at: now - 40 * day, by: 'Administrador' }],
      },
      {
        id: 'user-5',
        name: 'Ana Gómez',
        email: 'ana@example.com',
        passwordHash: hash('demo1234'),
        role: 'user',
        status: 'active',
        kycStatus: 'none',
        createdAt: now - 2 * day,
        lastActiveAt: now - 2 * day,
        virtualBalance: 10000,
        holdings: [],
        transactions: [],
        tags: ['lead'],
        notes: [],
      },
      {
        id: 'user-6',
        name: 'Javier Ruiz',
        email: 'javier@example.com',
        passwordHash: hash('demo1234'),
        role: 'user',
        status: 'active',
        kycStatus: 'pending',
        createdAt: now - 1 * day,
        lastActiveAt: now - 20 * 60 * 60 * 1000,
        virtualBalance: 10000,
        holdings: [],
        transactions: [],
        tags: ['lead', 'nuevo'],
        notes: [],
      },
      {
        id: 'user-7',
        name: 'Sofía Castro',
        email: 'sofia@example.com',
        passwordHash: hash('demo1234'),
        role: 'user',
        status: 'active',
        kycStatus: 'verified',
        createdAt: now - 75 * day,
        lastActiveAt: now - 10 * day,
        virtualBalance: 15200,
        holdings: [{ symbol: 'BTCUSD', quantity: 0.1, avgPrice: 58000 }],
        transactions: [tx('BTCUSD', 'buy', 0.1, 58000, 30)],
        tags: ['vip', 'activo'],
        notes: [],
      },
      {
        id: 'user-8',
        name: 'Pedro Navarro',
        email: 'pedro@example.com',
        passwordHash: hash('demo1234'),
        role: 'user',
        status: 'active',
        kycStatus: 'none',
        createdAt: now - 4 * 60 * 60 * 1000,
        lastActiveAt: now - 4 * 60 * 60 * 1000,
        virtualBalance: 10000,
        holdings: [],
        transactions: [],
        tags: ['lead'],
        notes: [],
      },
    ],
  };
}
